#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /enregistrer
    controller: App\Controller\AuthController::enregistrer
    methods: POST

login_check:
    path:     /login_check
    methods:  [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
api_login_check:
    path: /api/login_check