<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPlCHe4h\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPlCHe4h/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPlCHe4h.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPlCHe4h\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPlCHe4h\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PlCHe4h',
    'container.build_id' => 'dbfa66e1',
    'container.build_time' => 1578473657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPlCHe4h');
